package com.thomas.zirconmod.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ModAnimationDefinitions {

	public static final AnimationDefinition MOLE_IDLE = AnimationDefinition.Builder.withLength(4.5f).looping()
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(15f, -10f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.degreeVec(15f, 10f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.build();
	public static final AnimationDefinition MOLE_STOMP = AnimationDefinition.Builder.withLength(1.875f)
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("legs",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("legs",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("middle_left", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("middle_left", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_left", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.2917f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.625f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(1.2917f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7917f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_right", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.9167f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0833f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0417f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.build();
	public static final AnimationDefinition MOLE_WALK = AnimationDefinition.Builder.withLength(0.6766666f).looping()
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("middle_left", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.3f, -0.5f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("middle_left", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("middle_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0.3f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("middle_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("back_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0.3f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("back_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("back_right", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.3f, -0.5f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("back_right", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 0.3f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_right", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.3f, -0.5f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1667f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3333f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("front_right", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.build();
	public static final AnimationDefinition MOLE_ATTACK = AnimationDefinition.Builder.withLength(1f)
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0.2f, -0.2f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.2f, -0.2f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("lower", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("lower", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.build();
	public static final AnimationDefinition MOLE_SNIFF = AnimationDefinition.Builder.withLength(2f).addAnimation("mole",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("mole",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-63.99f, 17.66f, -9.54f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(-56.49f, 17.66f, -9.54f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-63.99f, 17.66f, -9.54f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(-63.99f, -17.66f, 9.54f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5f, KeyframeAnimations.degreeVec(-56.49f, -17.66f, 9.54f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-63.99f, -17.66f, 9.54f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("upper",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("upper", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.build();
	public static final AnimationDefinition MOLE_BURROW = AnimationDefinition.Builder.withLength(2f)
			.addAnimation("mole", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("mole", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833f, KeyframeAnimations.posVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.build();

	// Wood Golem
	public static final AnimationDefinition WOOD_GOLEM_IDLE = AnimationDefinition.Builder.withLength(0f).looping()
			.build();
	public static final AnimationDefinition WOOD_GOLEM_ATTACK = AnimationDefinition.Builder.withLength(1f)
			.addAnimation("arms",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 720f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("folder5", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 70f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder6", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 70f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder7", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, -70f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder8", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, -70f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(-70f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(-70f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder3", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(70f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("folder4", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25f, KeyframeAnimations.degreeVec(70f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
							AnimationChannel.Interpolations.LINEAR)))
			.build();
	public static final AnimationDefinition WOOD_GOLEM_WALK = AnimationDefinition.Builder.withLength(1f).looping()
			.addAnimation("front_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-17f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-16f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(-7f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(4f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(19f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("front_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(17f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(16f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(7f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-4f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(-19f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(-13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("back_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-17f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-16f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(-7f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(4f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(19f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("back_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(17f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(16f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(7f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-4f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(-19f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(-13f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();

	public static final AnimationDefinition NIMBULA_IDLE = AnimationDefinition.Builder.withLength(4f).looping()
			.addAnimation("ar",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ar",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ar2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.375f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.3433335f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 0.85f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.05f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.05f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5834335f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.375f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.scaleVec(1f, 1.05f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.6766667f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ar4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.875f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.2916765f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.25f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.875f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.75f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.875f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.125f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tendrils",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();
	public static final AnimationDefinition NIMBULA_WALK = AnimationDefinition.Builder.withLength(1f).looping()
			.addAnimation("ar", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("br", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("cr", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("dr", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("al", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("bl", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("cl", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("dl", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("bell",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.scaleVec(1.05f, 1.1f, 1.05f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();

	public static final AnimationDefinition WISP_FLAP = AnimationDefinition.Builder.withLength(2f).looping()
			.addAnimation("left_wing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 20f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_wing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -20f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.375f, KeyframeAnimations.degreeVec(-3f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(-3f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();
	
	
	public static final AnimationDefinition TEMPEST_WALK = AnimationDefinition.Builder.withLength(1f).looping()
			.addAnimation("ar", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("br", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("cr", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("dr", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("al", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("bl", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("cl", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("dl", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("bell",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.scaleVec(1.05f, 1.1f, 1.05f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();

	public static final AnimationDefinition TEMPEST_IDLE = AnimationDefinition.Builder.withLength(4f).looping()
			.addAnimation("ar",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ar",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ar2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.375f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.3433335f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 0.85f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.05f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.05f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5834335f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6766665f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.15f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1.1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-9f, 0f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.375f, KeyframeAnimations.degreeVec(5f, 0f, 7f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(-8f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.scaleVec(1f, 1.05f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.6766667f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3433335f, KeyframeAnimations.scaleVec(1f, 0.9f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ar4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("br4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.875f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cr4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.2916765f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dr4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("al4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.25f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("bl4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.875f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.5f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("cl4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(2f, 0f, -9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(1f, 0f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.75f, KeyframeAnimations.degreeVec(-8f, 0f, -4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-4f, 0f, 2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.875f, KeyframeAnimations.degreeVec(12.5f, 0f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("dl4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(4f, 0f, 6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.125f, KeyframeAnimations.degreeVec(-6f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tendrils",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.build();
}
